export const port = 80
export const domain = 'football.local.com'

export const listLeague = `http://${domain}:${port}/api/league/list`
export const listMatchByDay = 'http://football.local.com:80/api/match/list_matches_by_day'
export const listMatchByLeague = 'http://football.local.com:80/api/match/list_matches_by_league'
export const playerInfo = 'http://football.local.com:80/api/footballer/info'
export const clubInfo = 'http://football.local.com:80/api/club/info'
export const playerOfClub = 'http://football.local.com:80/api/club/listFootballer'
export const listPost = (page: number) => `http://football.local.com:80/api/post/get_post_list?page=${page}`
export const listPostByClub = (id: number) => `http://football.local.com:80/api/post/get_club_post/${id}`
export const listPostByPlayer = (id: number) => `http://football.local.com:80/api/post/get_footballer_post/${id}`
export const followingClub = 'http://football.local.com:80/api/followings/get_followings_club'
export const followingPlayer = 'http://football.local.com:80/api/followings/get_followings_footballer'
export const recommendedClub = 'http://football.local.com:80/api/followings/get_suggested_club'
export const recommendedPlayer = 'http://football.local.com:80/api/followings/get_suggested_player'
export const login = 'http://football.local.com:80/api/auth/login'
export const getUser = 'http://football.local.com:80/api/auth/get_user_infor'
export const getComment = 'http://football.local.com:80/api/comment/list_comment'
export const addComment = 'http://football.local.com:80/api/comment/add'
export const logOutUrl = 'http://football.local.com:80/api/auth/logout'
export const signupUrl = 'http://football.local.com:80/api/auth/signup'
export const delCmtUrl = 'http://football.local.com:80/api/comment/delete'
export const searchUrl = 'http://football.local.com:80/api/search/search_by_key'
export const getLikeUrl = 'http://football.local.com:80/api/like/list_user'
export const likeUrl = 'http://football.local.com:80/api/like/like_post'
export const editCmtUrl = 'http://football.local.com:80/api/comment/edit'
export const adminCreatePost = 'http://football.local.com:80/api/admin/post/create'
export const adminEditPost = 'http://football.local.com:80/api/admin/post/edit'
export const adminDelPost = 'http://football.local.com:80/api/admin/post/delete'
export const adminCreateClub = 'http://football.local.com:80/api/admin/club/create'
export const adminEditClub = 'http://football.local.com:80/api/admin/club/edit'
export const adminDelClub = 'http://football.local.com:80/api/admin/club/delete'
export const adminCreateFootballer = 'http://football.local.com:80/api/admin/footballer/create'
export const adminEditFootballer = 'http://football.local.com:80/api/admin/footballer/edit'
export const adminDelFootballer = 'http://football.local.com:80/api/admin/footballer/delete'
export const adminCreateLeague = 'http://football.local.com:80/api/admin/league/create'
export const adminEditLeague = 'http://football.local.com:80/api/admin/league/edit'
export const adminDelLeague = 'http://football.local.com:80/api/admin/league/delete'
export const adminCreateUser = 'http://football.local.com:80/api/admin/user/create'
export const adminEditUser = 'http://football.local.com:80/api/admin/user/edit'
export const adminDelUser = 'http://football.local.com:80/api/admin/user/delete'
export const adminCreateMatch = 'http://football.local.com:80/api/admin/match/create'
export const adminEditMatch = 'http://football.local.com:80/api/admin/match/edit'
export const adminDelMatch = 'http://football.local.com:80/api/admin/match/delete'
